---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
        when: ansible_distribution  != "Fedora"
      - name: Hello fact
        debug:
          msg: "{{ hello_fact }}"
        when: ansible_distribution  == "Fedora"
